### ISSUE TITLE
Media number of ports

### ISSUE THREAD

**Issue by SebastienBruckert** [ibc/libsdptransform#10]
Hello,
As described in the RFC here https://tools.ietf.org/html/rfc4566#section-5.14, there may be a number to describe how many ports the RTP/RTCP will use, like this:
`m=video 49170/2 RTP/AVP 31`

Since in the json, the port is a number, it would loose everything after the `/`. Is there any way to add that ? Thank you !

**Comment by ibc** [comment]
Wow, I didn't know that. BTW, is that really used anywhere today? I can add a `numPorts` field, but I've never seen that usage in any SDP.

**Comment by ibc** [comment]
Done in 1.2.2.

**Comment by SebastienBruckert** [comment]
Perfect thank you for your reactivity !
I'm jut a SDP beginner, and I have never seen this neither ; but I'm looking at a lot of RFC in details. I 'll let you know if I found something else.
