### ISSUE TITLE
How to modify Video Codecs

### ISSUE THREAD

**Issue by traw** [ibc/libsdptransform#2]
Here how I do, but couldn't parse codecs.
```
std::string modifySdp(std::string sdp) {
    Json session = sdptransform::parse(sdp);
    auto &video = session.at("media");
    video[1].at("payloads") = "120 126";
    return sdptransform::write(session);
}
```

sdp: contains valid sdp content.

**Comment by ibc** [comment]
Which is the exact question or issue/problem?

**Comment by traw** [comment]
Sorry, it was not the issue of this code, but I'd to remove all other relative fields as well. 
Field  like rtp, rtcpFb etc. Once I removed those fields along with codec payload it worked for me.
